// test/browser/image_annotation.spec.ts

import { expect, test } from "@playwright/test"

test("persists a nondestructive edit recipe with crop, preview, and annotation metadata", async ({ page }) => {
  await page.setViewportSize({ height: 1000, width: 1440 })
  await page.goto("/admin/login")
  await page.getByLabel("Email").fill("admin@example.test")
  await page.getByLabel("Password").fill("showcase-password")
  await page.getByRole("button", { name: "Sign In" }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await page.goto("/admin/image_annotation_editor")
  const canvas = page.getByRole("img", { name: /Source image editor/ })
  await expect(page.getByRole("img", { name: "Processed image preview" })).toBeVisible()
  const bounds = await canvas.boundingBox()
  if (!bounds) throw new Error("Image editor canvas was not rendered")
  await page.mouse.move(bounds.x + bounds.width * 0.12, bounds.y + bounds.height * 0.14)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * 0.78, bounds.y + bounds.height * 0.82)
  await page.mouse.up()
  await expect(page.getByText(/Crop 0.66 × 0.68/)).toBeVisible()
  await page.getByRole("button", { name: "Focal-point tool" }).click()
  await expect(page.getByLabel("focal x")).toHaveValue("0.5")
  await canvas.click({ position: { x: bounds.width * 0.25, y: bounds.height * 0.75 } })
  await expect(page.getByLabel("focal x")).toHaveValue(/0.25/)
  await canvas.press("ArrowRight")
  await page.getByText("Focal point and annotation region").click()
  await page.getByLabel("region x").fill("0.2")
  await page.getByLabel("region y").fill("0.2")
  await page.getByLabel("region width").fill("0.35")
  await page.getByLabel("region height").fill("0.4")
  await expect(canvas).toHaveAttribute("data-ready", "true")
  if (process.env.CAPTURE_SHOWCASE_SCREENSHOTS) {
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: "docs/screenshots/image-editor-workspace.png" })
  }
  await page.getByRole("slider", { name: "Brightness" }).fill("1.15")
  await page.getByLabel("Grayscale / B&W").check()
  await expect(canvas).toHaveAttribute("data-ready", "true")
  if (process.env.CAPTURE_SHOWCASE_SCREENSHOTS) {
    await page.getByRole("img", { name: "Processed image preview" }).screenshot({ path: "docs/screenshots/image-editor-processed.png" })
  }
  await page.getByRole("button", { name: "Save edit recipe" }).click()
  await expect(page.getByText("Image recipe saved.", { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel("focal x")).toHaveValue(/0.26/)
  await expect(page.getByLabel("Grayscale / B&W")).toBeChecked()
  await expect(page.getByRole("slider", { name: "Brightness" })).toHaveValue("1.15")
  await expect(page.getByText(/Crop 0.66 × 0.68/)).toBeVisible()
})
