// test/browser/workbench_laboratory.spec.ts
import { expect, test } from "@playwright/test"

test("Workbench 1.3 adapts the record workspace without replacing Rails behavior", async ({ page }) => {
  await page.goto("/admin/login")
  await page.getByLabel("Email").fill("admin@example.test")
  await page.getByLabel("Password").fill("showcase-password")
  await page.getByRole("button", { name: "Sign In" }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await page.goto("/admin/workbench_laboratory")
  await expect(page).toHaveTitle(/Workbench 1.3 — Heritage Laboratory/)
  const study = page.getByRole("region", { name: "Workbench 1.3 design study", exact: true })
  await expect(study).toBeVisible()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.reload()
    await expect(study).toBeVisible()
    await expect(study.locator("tbody a").first()).toHaveCSS("color", "rgb(255, 253, 244)")
    await expect(study.getByRole("button", { name: "Use", exact: true })).toHaveCSS("background-color", "rgb(255, 174, 56)")
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(study.getByRole("button", { name: "Use", exact: true })).toBeVisible()
    if (process.env.CAPTURE_SHOWCASE_SCREENSHOTS) {
      await page.screenshot({ fullPage: true, path: `docs/screenshots/workbench-13-${width}.png` })
    }
  }
  await study.getByLabel("Account status").selectOption("trial")
  await study.getByRole("button", { name: "Use", exact: true }).focus()
  await page.keyboard.press("Enter")
  await expect(page).toHaveURL(/status=trial/)
  await expect(study.locator("tbody tr")).toHaveCount(1)
  await expect(study.getByRole("status")).toContainText("trial")
  await study.getByRole("link", { name: "Reset", exact: true }).click()
  await expect(study.locator("tbody tr")).toHaveCount(6)
  await study.getByText("Reference & modern adaptations", { exact: true }).click()
  await expect(study.getByText(/Single-click links/)).toBeVisible()
  await page.emulateMedia({ reducedMotion: "reduce", forcedColors: "active" })
  await expect(study.getByLabel("Account status")).toBeVisible()
  await study.getByLabel("Account status").focus()
  expect(await study.getByLabel("Account status").evaluate(node => getComputedStyle(node).outlineStyle)).not.toBe("none")
  await page.emulateMedia({ reducedMotion: "no-preference", forcedColors: "none" })
  await study.getByRole("link", { name: "Open full Accounts directory" }).click()
  await expect(page).toHaveURL(/\/admin\/accounts$/)
  await expect(page.locator(".wb13")).toHaveCount(0)
})

test("Workbench form and links remain useful without JavaScript", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } })
  const page = await context.newPage()
  await page.goto("/admin/login")
  await page.getByLabel("Email").fill("admin@example.test")
  await page.getByLabel("Password").fill("showcase-password")
  await page.getByRole("button", { name: "Sign In" }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await page.goto("/admin/workbench_laboratory")
  await page.getByLabel("Account status").selectOption("trial")
  await page.getByRole("button", { name: "Use", exact: true }).click()
  await expect(page).toHaveURL(/status=trial/)
  await expect(page.locator(".wb13 tbody tr")).toHaveCount(1)
  await page.locator(".wb13 tbody a").first().click()
  await expect(page).toHaveURL(/\/admin\/accounts\/\d+$/)
  await context.close()
})
