# sig/spacecraft.rbs

module Spacecraft
  class Catalog
    COMPONENTS: Array[Hash[Symbol, String]]
    def self.ids: () -> Array[String]
  end
  class Serializer
    def initialize: (untyped model) -> void
    def as_json: () -> Hash[Symbol, untyped]
  end
  class Seed
    def self.call: (admin_user: untyped) -> untyped
  end
end
